# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0311bf48184d7975eee5661252f50aad78e37bbb51adde7292eeb27b8891835d151994df224fdf658c72943abfe54b39291fbe94b2e2c245edc7a55d8b650540

test:
  secret_key_base: 59c2a5b72e6a6e0ac62bbe3f692f9af20c968e930e67fdfdcc528054529328ecd9d416a2b4c6e42464c7485c5488dc7d9c7c22b71e862a1bb8d896d5d72ba721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
